### PR TITLE
Write Rendy backend for Turbine-Scene3D

### PR DESCRIPTION
**Pull request by aaruel**
This is a follow up to issue #70. My goal for this implementation was to leave as much of the original API the same as possible, which I've achieved for the most part aside from some quirks. 

~~In terms of dependencies, there are more crates introduced in this PR than I wanted (`serde_json` and `spirv-reflect`). The reason for that is, Rendy's exposure of SPIR-V reflection is minimal, leading to having to perform the reflection manually. I will probably open an issue on their repo addressing this. (amethyst/rendy#188)~~

Since Rendy/gfx-hal uses Winit, I used Piston's winit_window package but modified to be updated and work nicely with the `WindowSettings` builder. I will submit a PR on that repo so the dependency is an actual crate. (PistonDevelopers/winit_window#12)

Quirks:
- `Scene` manages the window by passing in `WindowSettings`
- The `UBOS_PER_FRAME_SIZE` constant determines how many draw calls (like `DrawTriangles`) there can be between frames. It's `4` for debugging but can be increased to something much larger.
- There's a certain structure the shaders must follow because of SPIR-V. Just keep in mind: 
    - Attributes layout locations are exact 
    - UBO at set 0 binding 0 contains all the uniforms (which should be matched if needed in both vert and frag stages)
    - Sampler2d is always at set 1 binding 0 
    - Inputs and outputs should have explicit locations
- Toggling SRGB and Blending are disabled for now.
- Drawing with multiple shaders is not tested but theoretically working.

Examples can be run at scene3d root as such `cargo run --example colored_cube --features vulkan`

### CODE REVIEW

**Comment by bvssvni** [comment]
winit_window 0.12.0 is now published.

**Comment by aaruel** [comment]
Thanks, updated `cargo.toml`

**Comment by aaruel** [comment]
`serde_json` is now removed, I missed that there actually was a Rendy method exposing the compiled SPIR-V data.

**Comment by bvssvni** [comment]
I've been trying to install Vulkan on Ubuntu to test this PR, but without success so far (got problems with NVidia graphics drivers).

**Comment by aaruel** [comment]
A lot of people using Rendy reported having trouble with Vulkan validation layers on multiple SDK versions. I was on 1.1.108.0 and the validation layers crashed completely. I updated to 1.1.114.0 and was able to run it, but also got an error about `VK_IMAGE_LAYOUT_UNDEFINED`, which is pretty commonly reported on the Discord (however it doesn't affect anything as far as I can tell). If you run the examples with `--release` it should run without the validation layers and avoid the problems altogether.

**Comment by bvssvni** [comment]
I got problems installing graphics drivers. Adding `--release` does not work. However, I can build it just fine.

I think this is a fine starting point.

Merging.

**Comment by bvssvni** [comment]
Thanks!

**Pull request merged**
